version: '3'
services:
  sole-file-validation-service:
    image: sole-file-validation-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always